# Generated by Django 2.0.5 on 2018-06-04 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='canteen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wte.Canteen'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wte.Item'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='up_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='up_users', to='wte.User'),
        ),
    ]
