# Generated by Django 2.0.5 on 2018-06-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wte', '0004_remove_comment_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canteen',
            name='intro',
            field=models.CharField(default='暂无简介', max_length=500),
        ),
        migrations.AlterField(
            model_name='canteen',
            name='pos',
            field=models.CharField(default='北京邮电大学沙河校区', max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='up_users',
            field=models.ManyToManyField(blank=True, related_name='up_comment', to='wte.User'),
        ),
    ]
