# Generated by Django 2.0.5 on 2018-06-20 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wte', '0005_auto_20180614_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='canteen_ename',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='comment',
            name='item_ename',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_openid',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='canteen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wte.Canteen'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wte.Item'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wte.User'),
        ),
    ]
