# Generated by Django 2.0.6 on 2018-07-13 22:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wte', '0006_auto_20180620_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='create-time'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='canteen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wte.Canteen'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wte.Item'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wte.User'),
        ),
    ]
