# Generated by Django 2.0.6 on 2018-07-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wte', '0007_auto_20180713_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
