# Generated by Django 2.0.5 on 2018-08-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wte', '0011_auto_20180820_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteen',
            name='close_day',
            field=models.CharField(default='{}', max_length=200),
        ),
        migrations.AlterField(
            model_name='canteen',
            name='timetable',
            field=models.CharField(default='{}', max_length=1024),
        ),
    ]
