# Generated by Django 2.0.5 on 2018-08-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wte', '0012_auto_20180821_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteen',
            name='pic_url',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
